services:
  - type: web
    name: scms-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    preDeployCommand: npm run migrate
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
